/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashRouteImport } from './routes/dash'
import { Route as DashIndexRouteImport } from './routes/dash/index'
import { Route as DashWorkersRouteImport } from './routes/dash/workers'
import { Route as DashVaultRouteImport } from './routes/dash/vault'
import { Route as DashTorrentsRouteImport } from './routes/dash/torrents'
import { Route as DashSyncRouteImport } from './routes/dash/sync'
import { Route as DashLoginRouteImport } from './routes/dash/login'
import { Route as DashListsRouteImport } from './routes/dash/lists'
import { Route as DashVaultIndexRouteImport } from './routes/dash/vault/index'
import { Route as DashTorrentsIndexRouteImport } from './routes/dash/torrents/index'
import { Route as DashSyncIndexRouteImport } from './routes/dash/sync/index'
import { Route as DashListsIndexRouteImport } from './routes/dash/lists/index'
import { Route as DashVaultTraktAccountsRouteImport } from './routes/dash/vault/trakt-accounts'
import { Route as DashVaultTorznabIndexersRouteImport } from './routes/dash/vault/torznab-indexers'
import { Route as DashVaultStremioAccountsRouteImport } from './routes/dash/vault/stremio-accounts'
import { Route as DashTorrentsIndexersSyncRouteImport } from './routes/dash/torrents/indexers-sync'
import { Route as DashSyncStremioTraktRouteImport } from './routes/dash/sync/stremio-trakt'
import { Route as DashSyncStremioStremioRouteImport } from './routes/dash/sync/stremio-stremio'

const DashRoute = DashRouteImport.update({
  id: '/dash',
  path: '/dash',
  getParentRoute: () => rootRouteImport,
} as any)
const DashIndexRoute = DashIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashRoute,
} as any)
const DashWorkersRoute = DashWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => DashRoute,
} as any)
const DashVaultRoute = DashVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => DashRoute,
} as any)
const DashTorrentsRoute = DashTorrentsRouteImport.update({
  id: '/torrents',
  path: '/torrents',
  getParentRoute: () => DashRoute,
} as any)
const DashSyncRoute = DashSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => DashRoute,
} as any)
const DashLoginRoute = DashLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => DashRoute,
} as any)
const DashListsRoute = DashListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => DashRoute,
} as any)
const DashVaultIndexRoute = DashVaultIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashVaultRoute,
} as any)
const DashTorrentsIndexRoute = DashTorrentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashTorrentsRoute,
} as any)
const DashSyncIndexRoute = DashSyncIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashSyncRoute,
} as any)
const DashListsIndexRoute = DashListsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashListsRoute,
} as any)
const DashVaultTraktAccountsRoute = DashVaultTraktAccountsRouteImport.update({
  id: '/trakt-accounts',
  path: '/trakt-accounts',
  getParentRoute: () => DashVaultRoute,
} as any)
const DashVaultTorznabIndexersRoute =
  DashVaultTorznabIndexersRouteImport.update({
    id: '/torznab-indexers',
    path: '/torznab-indexers',
    getParentRoute: () => DashVaultRoute,
  } as any)
const DashVaultStremioAccountsRoute =
  DashVaultStremioAccountsRouteImport.update({
    id: '/stremio-accounts',
    path: '/stremio-accounts',
    getParentRoute: () => DashVaultRoute,
  } as any)
const DashTorrentsIndexersSyncRoute =
  DashTorrentsIndexersSyncRouteImport.update({
    id: '/indexers-sync',
    path: '/indexers-sync',
    getParentRoute: () => DashTorrentsRoute,
  } as any)
const DashSyncStremioTraktRoute = DashSyncStremioTraktRouteImport.update({
  id: '/stremio-trakt',
  path: '/stremio-trakt',
  getParentRoute: () => DashSyncRoute,
} as any)
const DashSyncStremioStremioRoute = DashSyncStremioStremioRouteImport.update({
  id: '/stremio-stremio',
  path: '/stremio-stremio',
  getParentRoute: () => DashSyncRoute,
} as any)

export interface FileRoutesByFullPath {
  '/dash': typeof DashRouteWithChildren
  '/dash/lists': typeof DashListsRouteWithChildren
  '/dash/login': typeof DashLoginRoute
  '/dash/sync': typeof DashSyncRouteWithChildren
  '/dash/torrents': typeof DashTorrentsRouteWithChildren
  '/dash/vault': typeof DashVaultRouteWithChildren
  '/dash/workers': typeof DashWorkersRoute
  '/dash/': typeof DashIndexRoute
  '/dash/sync/stremio-stremio': typeof DashSyncStremioStremioRoute
  '/dash/sync/stremio-trakt': typeof DashSyncStremioTraktRoute
  '/dash/torrents/indexers-sync': typeof DashTorrentsIndexersSyncRoute
  '/dash/vault/stremio-accounts': typeof DashVaultStremioAccountsRoute
  '/dash/vault/torznab-indexers': typeof DashVaultTorznabIndexersRoute
  '/dash/vault/trakt-accounts': typeof DashVaultTraktAccountsRoute
  '/dash/lists/': typeof DashListsIndexRoute
  '/dash/sync/': typeof DashSyncIndexRoute
  '/dash/torrents/': typeof DashTorrentsIndexRoute
  '/dash/vault/': typeof DashVaultIndexRoute
}
export interface FileRoutesByTo {
  '/dash/login': typeof DashLoginRoute
  '/dash/workers': typeof DashWorkersRoute
  '/dash': typeof DashIndexRoute
  '/dash/sync/stremio-stremio': typeof DashSyncStremioStremioRoute
  '/dash/sync/stremio-trakt': typeof DashSyncStremioTraktRoute
  '/dash/torrents/indexers-sync': typeof DashTorrentsIndexersSyncRoute
  '/dash/vault/stremio-accounts': typeof DashVaultStremioAccountsRoute
  '/dash/vault/torznab-indexers': typeof DashVaultTorznabIndexersRoute
  '/dash/vault/trakt-accounts': typeof DashVaultTraktAccountsRoute
  '/dash/lists': typeof DashListsIndexRoute
  '/dash/sync': typeof DashSyncIndexRoute
  '/dash/torrents': typeof DashTorrentsIndexRoute
  '/dash/vault': typeof DashVaultIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dash': typeof DashRouteWithChildren
  '/dash/lists': typeof DashListsRouteWithChildren
  '/dash/login': typeof DashLoginRoute
  '/dash/sync': typeof DashSyncRouteWithChildren
  '/dash/torrents': typeof DashTorrentsRouteWithChildren
  '/dash/vault': typeof DashVaultRouteWithChildren
  '/dash/workers': typeof DashWorkersRoute
  '/dash/': typeof DashIndexRoute
  '/dash/sync/stremio-stremio': typeof DashSyncStremioStremioRoute
  '/dash/sync/stremio-trakt': typeof DashSyncStremioTraktRoute
  '/dash/torrents/indexers-sync': typeof DashTorrentsIndexersSyncRoute
  '/dash/vault/stremio-accounts': typeof DashVaultStremioAccountsRoute
  '/dash/vault/torznab-indexers': typeof DashVaultTorznabIndexersRoute
  '/dash/vault/trakt-accounts': typeof DashVaultTraktAccountsRoute
  '/dash/lists/': typeof DashListsIndexRoute
  '/dash/sync/': typeof DashSyncIndexRoute
  '/dash/torrents/': typeof DashTorrentsIndexRoute
  '/dash/vault/': typeof DashVaultIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dash'
    | '/dash/lists'
    | '/dash/login'
    | '/dash/sync'
    | '/dash/torrents'
    | '/dash/vault'
    | '/dash/workers'
    | '/dash/'
    | '/dash/sync/stremio-stremio'
    | '/dash/sync/stremio-trakt'
    | '/dash/torrents/indexers-sync'
    | '/dash/vault/stremio-accounts'
    | '/dash/vault/torznab-indexers'
    | '/dash/vault/trakt-accounts'
    | '/dash/lists/'
    | '/dash/sync/'
    | '/dash/torrents/'
    | '/dash/vault/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dash/login'
    | '/dash/workers'
    | '/dash'
    | '/dash/sync/stremio-stremio'
    | '/dash/sync/stremio-trakt'
    | '/dash/torrents/indexers-sync'
    | '/dash/vault/stremio-accounts'
    | '/dash/vault/torznab-indexers'
    | '/dash/vault/trakt-accounts'
    | '/dash/lists'
    | '/dash/sync'
    | '/dash/torrents'
    | '/dash/vault'
  id:
    | '__root__'
    | '/dash'
    | '/dash/lists'
    | '/dash/login'
    | '/dash/sync'
    | '/dash/torrents'
    | '/dash/vault'
    | '/dash/workers'
    | '/dash/'
    | '/dash/sync/stremio-stremio'
    | '/dash/sync/stremio-trakt'
    | '/dash/torrents/indexers-sync'
    | '/dash/vault/stremio-accounts'
    | '/dash/vault/torznab-indexers'
    | '/dash/vault/trakt-accounts'
    | '/dash/lists/'
    | '/dash/sync/'
    | '/dash/torrents/'
    | '/dash/vault/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashRoute: typeof DashRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dash': {
      id: '/dash'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash/': {
      id: '/dash/'
      path: '/'
      fullPath: '/dash/'
      preLoaderRoute: typeof DashIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/workers': {
      id: '/dash/workers'
      path: '/workers'
      fullPath: '/dash/workers'
      preLoaderRoute: typeof DashWorkersRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/vault': {
      id: '/dash/vault'
      path: '/vault'
      fullPath: '/dash/vault'
      preLoaderRoute: typeof DashVaultRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/torrents': {
      id: '/dash/torrents'
      path: '/torrents'
      fullPath: '/dash/torrents'
      preLoaderRoute: typeof DashTorrentsRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/sync': {
      id: '/dash/sync'
      path: '/sync'
      fullPath: '/dash/sync'
      preLoaderRoute: typeof DashSyncRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/login': {
      id: '/dash/login'
      path: '/login'
      fullPath: '/dash/login'
      preLoaderRoute: typeof DashLoginRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/lists': {
      id: '/dash/lists'
      path: '/lists'
      fullPath: '/dash/lists'
      preLoaderRoute: typeof DashListsRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/vault/': {
      id: '/dash/vault/'
      path: '/'
      fullPath: '/dash/vault/'
      preLoaderRoute: typeof DashVaultIndexRouteImport
      parentRoute: typeof DashVaultRoute
    }
    '/dash/torrents/': {
      id: '/dash/torrents/'
      path: '/'
      fullPath: '/dash/torrents/'
      preLoaderRoute: typeof DashTorrentsIndexRouteImport
      parentRoute: typeof DashTorrentsRoute
    }
    '/dash/sync/': {
      id: '/dash/sync/'
      path: '/'
      fullPath: '/dash/sync/'
      preLoaderRoute: typeof DashSyncIndexRouteImport
      parentRoute: typeof DashSyncRoute
    }
    '/dash/lists/': {
      id: '/dash/lists/'
      path: '/'
      fullPath: '/dash/lists/'
      preLoaderRoute: typeof DashListsIndexRouteImport
      parentRoute: typeof DashListsRoute
    }
    '/dash/vault/trakt-accounts': {
      id: '/dash/vault/trakt-accounts'
      path: '/trakt-accounts'
      fullPath: '/dash/vault/trakt-accounts'
      preLoaderRoute: typeof DashVaultTraktAccountsRouteImport
      parentRoute: typeof DashVaultRoute
    }
    '/dash/vault/torznab-indexers': {
      id: '/dash/vault/torznab-indexers'
      path: '/torznab-indexers'
      fullPath: '/dash/vault/torznab-indexers'
      preLoaderRoute: typeof DashVaultTorznabIndexersRouteImport
      parentRoute: typeof DashVaultRoute
    }
    '/dash/vault/stremio-accounts': {
      id: '/dash/vault/stremio-accounts'
      path: '/stremio-accounts'
      fullPath: '/dash/vault/stremio-accounts'
      preLoaderRoute: typeof DashVaultStremioAccountsRouteImport
      parentRoute: typeof DashVaultRoute
    }
    '/dash/torrents/indexers-sync': {
      id: '/dash/torrents/indexers-sync'
      path: '/indexers-sync'
      fullPath: '/dash/torrents/indexers-sync'
      preLoaderRoute: typeof DashTorrentsIndexersSyncRouteImport
      parentRoute: typeof DashTorrentsRoute
    }
    '/dash/sync/stremio-trakt': {
      id: '/dash/sync/stremio-trakt'
      path: '/stremio-trakt'
      fullPath: '/dash/sync/stremio-trakt'
      preLoaderRoute: typeof DashSyncStremioTraktRouteImport
      parentRoute: typeof DashSyncRoute
    }
    '/dash/sync/stremio-stremio': {
      id: '/dash/sync/stremio-stremio'
      path: '/stremio-stremio'
      fullPath: '/dash/sync/stremio-stremio'
      preLoaderRoute: typeof DashSyncStremioStremioRouteImport
      parentRoute: typeof DashSyncRoute
    }
  }
}

interface DashListsRouteChildren {
  DashListsIndexRoute: typeof DashListsIndexRoute
}

const DashListsRouteChildren: DashListsRouteChildren = {
  DashListsIndexRoute: DashListsIndexRoute,
}

const DashListsRouteWithChildren = DashListsRoute._addFileChildren(
  DashListsRouteChildren,
)

interface DashSyncRouteChildren {
  DashSyncStremioStremioRoute: typeof DashSyncStremioStremioRoute
  DashSyncStremioTraktRoute: typeof DashSyncStremioTraktRoute
  DashSyncIndexRoute: typeof DashSyncIndexRoute
}

const DashSyncRouteChildren: DashSyncRouteChildren = {
  DashSyncStremioStremioRoute: DashSyncStremioStremioRoute,
  DashSyncStremioTraktRoute: DashSyncStremioTraktRoute,
  DashSyncIndexRoute: DashSyncIndexRoute,
}

const DashSyncRouteWithChildren = DashSyncRoute._addFileChildren(
  DashSyncRouteChildren,
)

interface DashTorrentsRouteChildren {
  DashTorrentsIndexersSyncRoute: typeof DashTorrentsIndexersSyncRoute
  DashTorrentsIndexRoute: typeof DashTorrentsIndexRoute
}

const DashTorrentsRouteChildren: DashTorrentsRouteChildren = {
  DashTorrentsIndexersSyncRoute: DashTorrentsIndexersSyncRoute,
  DashTorrentsIndexRoute: DashTorrentsIndexRoute,
}

const DashTorrentsRouteWithChildren = DashTorrentsRoute._addFileChildren(
  DashTorrentsRouteChildren,
)

interface DashVaultRouteChildren {
  DashVaultStremioAccountsRoute: typeof DashVaultStremioAccountsRoute
  DashVaultTorznabIndexersRoute: typeof DashVaultTorznabIndexersRoute
  DashVaultTraktAccountsRoute: typeof DashVaultTraktAccountsRoute
  DashVaultIndexRoute: typeof DashVaultIndexRoute
}

const DashVaultRouteChildren: DashVaultRouteChildren = {
  DashVaultStremioAccountsRoute: DashVaultStremioAccountsRoute,
  DashVaultTorznabIndexersRoute: DashVaultTorznabIndexersRoute,
  DashVaultTraktAccountsRoute: DashVaultTraktAccountsRoute,
  DashVaultIndexRoute: DashVaultIndexRoute,
}

const DashVaultRouteWithChildren = DashVaultRoute._addFileChildren(
  DashVaultRouteChildren,
)

interface DashRouteChildren {
  DashListsRoute: typeof DashListsRouteWithChildren
  DashLoginRoute: typeof DashLoginRoute
  DashSyncRoute: typeof DashSyncRouteWithChildren
  DashTorrentsRoute: typeof DashTorrentsRouteWithChildren
  DashVaultRoute: typeof DashVaultRouteWithChildren
  DashWorkersRoute: typeof DashWorkersRoute
  DashIndexRoute: typeof DashIndexRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashListsRoute: DashListsRouteWithChildren,
  DashLoginRoute: DashLoginRoute,
  DashSyncRoute: DashSyncRouteWithChildren,
  DashTorrentsRoute: DashTorrentsRouteWithChildren,
  DashVaultRoute: DashVaultRouteWithChildren,
  DashWorkersRoute: DashWorkersRoute,
  DashIndexRoute: DashIndexRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashRoute: DashRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
